version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - my-network

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
